config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :links
  root to: 'links#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  def twitter_link
    "https://twitter.com/intent/tweet?text=#{comment.gsub(/[\s]/, "%20")}&url=#{source}"
  end

  def twitter_anchor
    <<-HEREDOC
    <a href="#{twitter_link}">#{title}</a>
    HEREDOC
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show
    @link = Link.find(params[:id])
  end

  def new
  end

  def create
    @link = Link.new(link_params)
    @link.save
    redirect_to @link
  end

  private

  def link_params
    params.require(:link).permit(:source, :comment, :title)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Social Share Links', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'New Link', new_link_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Share Links" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Share Links" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800i|Roboto+Mono" rel="stylesheet">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/links/new.html.erb
<% content_for :title do %>New Link<% end %>
<div class="row">
  <div class="small-12 medium-8 small-centered columns">
    <h1 class="text-center">Social Share Links</h1>
    <%= form_for :link, url: links_path do |f| %>
      <p>
        <%= f.label :source %>
        <%= f.text_field :source %>
      </p>

      <p>
        <%= f.label :comment %>
        <%= f.text_field :comment %>
        <em id="comment-length">116 Characters Left</em>
      </p>

      <p>
        <%= f.label :title %>
        <%= f.text_field :title, value: "Tweet This" %>
        <em>For HTML Anchor Link Only</em>
      </p>

      <p>
        <%= f.submit class: 'button' %>
      </p>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<% content_for :title do %>Results<% end %>
<div class="row">
  <div class="small-12 medium-8 small-centered columns">
    <p>
      <strong>Source URL: </strong><br>
      <span class="code-text"><%= @link.source %></span>
    </p>
    <p>
      <strong>Comment:</strong><br>
      <span class="code-text"><%= @link.comment %></span>
    </p>
    <p>
      <strong>Twitter Link:</strong><br>
      <span class="code-text"><%= @link.twitter_link %></span>
    </p>
    <p>
      <strong>Twitter </strong><span class="code-text">anchor</span><strong> Tag:</strong><br>
      <span class="code-text"><%= @link.twitter_anchor %></span>
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>